#!/usr/bin/env python3
"""Create a safe Tabletop Librarian development source bundle.

The bundler is intentionally deny-list based: source files and newly-added source
folders are included automatically unless they are known runtime/generated data.
This is for development handoff bundles, not end-user release packaging.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
from pathlib import Path
import subprocess
import sys
import tarfile
from datetime import datetime
from typing import Iterable

PROJECT_NAME = "TTLibrarian"

# Entire directories that are never useful in a source handoff bundle.
EXCLUDED_DIR_NAMES = {
    ".git",
    ".venv",
    "venv",
    "env",
    ".env",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".nox",
    ".idea",
    ".vscode",
    "node_modules",
    "backups",
    ".update_backups",
    "logs",
    "log",
    "cache",
    "caches",
    "models",
    "dist",
    "build",
    "site",
}

# Runtime-heavy directories can appear at different levels in TTL.
EXCLUDED_PATH_PARTS = {
    "embeddings",
    "indexes",
    "indices",
    "ocr_output",
    "ocr_cache",
    "cover_cache",
    "comic_cache",
    "tmp",
    "temp",
}

EXCLUDED_FILE_GLOBS = (
    "*.pyc",
    "*.pyo",
    "*.log",
    "*.pid",
    "*.sqlite",
    "*.sqlite3",
    "*.db",
    "*.gguf",
    "*.bin",
    "*.safetensors",
    "*.pt",
    "*.pth",
    "*.onnx",
    "*.tar",
    "*.tar.gz",
    "*.tgz",
    "*.zip",
)

# These files are generated by the bundler itself and must never recurse into a
# subsequent handoff bundle.
EXCLUDED_GENERATED_FILES = {
    "PROJECT_TREE.txt",
    "BUNDLE_INFO.txt",
}

# Under data/, only source-controlled fixtures/system packs belong in a source
# handoff. Runtime config, manifests, auth state, characters and uploaded books
# must stay local.
DATA_ALLOWED_PREFIXES = (
    Path("data/system_packs"),
)

REQUIRED_FILES = (
    Path("run.py"),
    Path("pyproject.toml"),
    Path("app/__init__.py"),
)

# These release-critical source areas are checked explicitly. The deny-list
# design means future source areas are included without editing this script,
# while these checks catch accidental bundling from the wrong tree.
REQUIRED_DIRS = (
    Path("app"),
    Path("data/system_packs"),
)


def is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def is_excluded_directory(name: str) -> bool:
    return (
        name in EXCLUDED_DIR_NAMES
        or name in EXCLUDED_PATH_PARTS
        or name.endswith(".egg-info")
    )


def should_include(rel: Path, output_path: Path, root: Path) -> tuple[bool, str]:
    if not rel.parts:
        return False, "root"

    if any(is_excluded_directory(part) for part in rel.parts[:-1]):
        return False, "excluded/generated directory"

    if rel.name in EXCLUDED_GENERATED_FILES:
        return False, "generated bundle metadata"

    if any(fnmatch.fnmatch(rel.name, pat) for pat in EXCLUDED_FILE_GLOBS):
        return False, "generated/binary/archive file"

    # Keep secrets and local environment files out, but retain normal examples.
    lower = rel.name.lower()
    if lower in {".env", ".env.local", "credentials.json", "secrets.json"}:
        return False, "credentials/environment file"
    if lower.startswith(".env.") and not lower.endswith((".example", ".sample", ".template")):
        return False, "credentials/environment file"

    if rel.parts[0] == "data":
        if not any(rel == prefix or is_relative_to(rel, prefix) for prefix in DATA_ALLOWED_PREFIXES):
            return False, "runtime data"

    absolute = root / rel
    try:
        if absolute.resolve() == output_path.resolve():
            return False, "output archive"
    except FileNotFoundError:
        pass

    return True, ""


def iter_files(root: Path, output_path: Path) -> Iterable[tuple[Path, Path]]:
    for current, dirnames, filenames in os.walk(root):
        current_path = Path(current)
        rel_dir = current_path.relative_to(root)

        # Prune whole excluded directory names early for speed.
        dirnames[:] = sorted(d for d in dirnames if not is_excluded_directory(d))

        for name in sorted(filenames):
            path = current_path / name
            rel = rel_dir / name if rel_dir.parts else Path(name)
            include, _ = should_include(rel, output_path, root)
            if include:
                yield path, rel


def git_text(root: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(root), *args],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        return result.stdout.strip()
    except OSError:
        return ""


def validate_root(root: Path) -> list[str]:
    problems: list[str] = []
    for rel in REQUIRED_FILES:
        if not (root / rel).is_file():
            problems.append(f"missing required file: {rel}")
    for rel in REQUIRED_DIRS:
        if not (root / rel).is_dir():
            problems.append(f"missing required directory: {rel}/")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a safe TTLibrarian development source bundle")
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="TTLibrarian project root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory for the archive (default: project parent)",
    )
    parser.add_argument("--dry-run", action="store_true", help="List what would be bundled without writing an archive")
    parser.add_argument("--list", action="store_true", help="Print every included file")
    args = parser.parse_args()

    root = args.project_root.expanduser().resolve()
    problems = validate_root(root)
    if problems:
        print("Refusing to bundle this directory:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 2

    stamp = datetime.now().astimezone().strftime("%Y%m%d_%H%M%S")
    output_dir = (args.output_dir.expanduser().resolve() if args.output_dir else root.parent)
    output_dir.mkdir(parents=True, exist_ok=True)
    archive = output_dir / f"TTLibrarian_source_bundle_{stamp}.tar.gz"

    files = list(iter_files(root, archive))
    rels = [rel for _, rel in files]

    # A pipelines/ directory is not universal enough to make root validation
    # fail, but if built-in presets exist locally they are included automatically.
    # Report the count so an incomplete handoff is obvious.
    pipeline_files = [rel for rel in rels if rel.parts and rel.parts[0] == "pipelines"]

    total_bytes = sum(path.stat().st_size for path, _ in files if path.is_file())
    print(f"Project: {root}")
    print(f"Files:   {len(files)}")
    print(f"Size:    {total_bytes / (1024 * 1024):.2f} MiB before compression")
    print(f"Pipelines included: {len(pipeline_files)} file(s)")

    if args.list or args.dry_run:
        for rel in rels:
            print(rel.as_posix())

    if args.dry_run:
        return 0

    created = datetime.now().astimezone().isoformat(timespec="seconds")
    commit = git_text(root, "rev-parse", "HEAD") or "unavailable"
    status = git_text(root, "status", "--short") or "clean or unavailable"

    bundle_info = (
        "Tabletop Librarian development source bundle\n"
        f"Created: {created}\n"
        f"Source: {root}\n"
        f"Files included: {len(files)}\n"
        f"Uncompressed source size: {total_bytes} bytes\n"
        f"Pipeline files included: {len(pipeline_files)}\n\n"
        "Explicitly NOT included:\n"
        "  .git / virtual environments / IDE state\n"
        "  backups / logs / caches / generated indexes / embeddings / models\n"
        "  uploaded library documents / OCR output / generated reader caches\n"
        "  runtime data except data/system_packs\n"
        "  credentials / .env files / API keys\n"
        "  previous archives and generated bundle metadata\n\n"
        f"Git commit: {commit}\n\n"
        f"Git status:\n{status}\n"
    )
    project_tree = "\n".join(f"./{rel.as_posix()}" for rel in rels) + "\n"

    with tarfile.open(archive, "w:gz", format=tarfile.PAX_FORMAT) as tf:
        for path, rel in files:
            tf.add(path, arcname=f"{PROJECT_NAME}/{rel.as_posix()}", recursive=False)

        for name, text in (("BUNDLE_INFO.txt", bundle_info), ("PROJECT_TREE.txt", project_tree)):
            data = text.encode("utf-8")
            info = tarfile.TarInfo(name=f"{PROJECT_NAME}/{name}")
            info.size = len(data)
            info.mtime = int(datetime.now().timestamp())
            import io
            tf.addfile(info, io.BytesIO(data))

    print(f"Created: {archive}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
